name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup Android NDK
      run: |
        wget https://dl.google.com/android/repository/android-ndk-r21-linux-x86_64.zip
        unzip android-ndk-r21-linux-x86_64.zip
    - name: Build
      run: |
        ANDROID_NDK_HOME=./android-ndk-r21 ./build.sh
        zip -jr ih8sn-aarch64.zip out/target/arm64-v8a/*
        zip -jr ih8sn-armv7a.zip out/target/armeabi-v7a/*
        zip -jr ih8sn-i686.zip out/target/x86/*
        zip -jr ih8sn-x86_64.zip out/target/x86_64/*
    - uses: actions/upload-artifact@v1
      with:
        name: ih8sn (AArch64)
        path: ih8sn-aarch64.zip
    - uses: actions/upload-artifact@v1
      with:
        name: ih8sn (ARMv7-A)
        path: ih8sn-armv7a.zip
    - uses: actions/upload-artifact@v1
      with:
        name: ih8sn (i686)
        path: ih8sn-i686.zip
    - uses: actions/upload-artifact@v1
      with:
        name: ih8sn (x86_64)
        path: ih8sn-x86_64.zip
    - uses: marvinpinto/action-automatic-releases@latest
      if: github.ref == 'refs/heads/master'
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: false
        title: "${{ env.GITHUB_SHA }}"
        files: |
          ih8sn-aarch64.zip
          ih8sn-armv7a.zip
          ih8sn-i686.zip
          ih8sn-x86_64.zip
